ALTER TABLE users
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN password SET NOT NULL;