spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true

  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080

jwt:
  secret: dGhpc0lzQUdvb2RTZWNyZXRLZXlGb3JKV1RUaGF0SXNBVE1lYXN0MjU2Qml0c0xvbmdGb3JTZWN1cml0eVB1cnBvc2Vz
  expiration: 86400

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
