spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fistein_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    problemdetails:
      enabled: true

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  http2:
    enabled: true

jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:86400}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:}

logging:
  level:
    com.fistein: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/fistein.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized