spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fistein_db
    username: postgres
    password: Ysn2025!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080

jwt:
  secret: dGhpc0lzQUdvb2RTZWNyZXRLZXlGb3JKV1RUaGF0SXNBVE1lYXN0MjU2Qml0c0xvbmdGb3JTZWN1cml0eVB1cnBvc2Vz
  expiration: 86400

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
