spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fistein_db
    username: postgres
    password: Ysn2025!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
